name       : python-zope.proxy
version    : 4.3.1
release    : 1
source     :
    - https://github.com/zopefoundation/zope.proxy/archive/4.3.1.tar.gz : 3c1bd5ca0e15ef9bcd18269db02b3c8050edcbc934b99f7ccfcc1d79e166d0c6
license    : ZPL-2.1
component  : programming.python
summary    : Generic transparent proxies via a C extension module
description: |
    Proxies are special objects which serve as mostly-transparent wrappers around another object, intervening in the apparent behavior of the wrapped object only when necessary to apply the policy (e.g., access checking, location brokering, etc.) for which the proxy is responsible.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-zope.interface
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
