name       : python-zope.proxy
version    : 4.4.0
release    : 7
source     :
    - https://github.com/zopefoundation/zope.proxy/archive/refs/tags/4.4.0.tar.gz : fbc7777f45d5d355188aa5a4cceb9f74e173f325763b591800cf6a1645bfc993
license    : ZPL-2.1
component  : programming.python
summary    : Generic transparent proxies via a C extension module
description: |
    Proxies are special objects which serve as mostly-transparent wrappers around another object, intervening in the apparent behavior of the wrapped object only when necessary to apply the policy (e.g., access checking, location brokering, etc.) for which the proxy is responsible.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-zope.interface
build      : |
    %python3_setup
install    : |
    %python3_install
